### PR TITLE
Add the shared lib for armeabi-v7a.

### PR DESCRIPTION
**Pull request by m4gr3d**

### CODE REVIEW

**Comment by NeoSpark314** [comment]
In which cases is the v7a abi version needed? Does the GO require this or is this for GearVR compatibility?

**Comment by m4gr3d** [comment]
GearVR compatibility and additional flexibility for devs. 
For example, if the project already makes use of other shared native libs then the developer has the option of which to use since Android can't easily handle shared libs of different architectures.

**Comment by NeoSpark314** [comment]
Thanks for the info; the choice when using already existing libraries makes sense. Regarding GearVR support. Is the plan for godot_oculus_mobile to support GearVR for the 3.2 release? If so I think we need to make sure to not upgrade to the newest VrApi because as I understood this here: https://developer.oculus.com/blog/gear-vr-app-development-no-longer-supported-from-sdk-suite-142-and-future-versions/ starting with Moblie SDK 1.27 GearVR will not be supported anymore.

**Comment by BastiaanOlij** [comment]
I don't see what harm it does to include both architectures, just need to keep in mind to compile both each time we update the version

**Review by BastiaanOlij — APPROVED** [review]

**Comment by BastiaanOlij** [comment]
> Regarding GearVR support. Is the plan for godot_oculus_mobile to support GearVR for the 3.2 release?

The GearVR is dead, I don't really see a point to hold ourselves back just to support it.

**Pull request merged**
